### PR TITLE
update master readme to include cookiecutter branch information

### PR DESCRIPTION
**Pull request by sosey**
This adds a pointer in the readme to the cookiecutter branch

### CODE REVIEW

**Comment by sosey** [comment]
Feel free to add formatting edits to the pr if you like

**Comment by pllim** [comment]
@sosey, I can't. I don't have write access to this repo.

**Comment by pllim** [comment]
Note: Fix #19

**Comment by sosey** [comment]
can't you pr to my branch?

**Comment by pllim** [comment]
Sure.

**Pull request merged**
