### PR TITLE
Add basic travis and rtd files and move the docs theme to the released stsci template

### LINKED ISSUE #2: Update the docs to include the release sphinx template
The current structure of the docs contains the old hack before the stsci_rtd_theme was released

### PR DESCRIPTION
**Pull request by sosey**
Fixes #2 
- removes the special code for the RTD template in favor of the stsci_rtd_theme that was made last year
- adds a basic travis file for testing
- adds basic RTD files for doc building 
- added build_sphinx to the setup 

@pllim take a look at the travis files and see if I missed anything? I already verified this builds on RTD.

### CODE REVIEW

**Comment by pllim** [comment]
IMHO Travis YML should run a test from this repo (can be a dummy test) rather than refer to JWST.

**Comment by sosey** [comment]
yah, just realized that was like that after I tagged you  :)

**Comment by pllim** [comment]
> I already verified this builds on RTD

@sosey , what is the RTD link?

**Comment by sosey** [comment]
http://test-stsci-rtd-theme.readthedocs.io/index.html

**Pull request merged**
