### PR TITLE
DOC: Point to real RTD badge

### PR DESCRIPTION
**Pull request by pllim**
Might as well?

This is a follow-up of #6.

### CODE REVIEW

**Comment by sosey** [comment]
no, I just want to use that for my own testing.

**Comment by pllim** [comment]
Shouldn't we build it properly and use a nice green shiny badge? As you said, it is already working.

**Comment by sosey** [comment]
I think it's better to make sure the badge shows unknown, so that users have a visual cue they forgot to change link names somewhere...

**Comment by pllim** [comment]
Hmm ok.

**Comment by sosey** [comment]
...from the point of view that we wont really be updating the docs for the package template, or very rarely, so the badge isn't as instructive for us (and we should check they work before pushing if we do), but for new users they may not understand the badges right away and having a visual cue might help them as they use the template for their own packages.

**Pull request closed without merging**
