### PR TITLE
updated readme with install instructions

### PR DESCRIPTION
**Pull request by stscicrawford**
Updated installation instructions.   This includes the instructions for how to use cookie cutter to createa . package. 

This branch is a fork of the astropy package template with updates to enable STScI package requirements and branding.

### CODE REVIEW

**Comment by pllim** [comment]
Oh, I didn't know we switched to cookiecutter here. In that case, we should also make that the default branch, not `master`. I don't have write access here, so you'll have to wait for @sosey to review.

**Comment by stscicrawford** [comment]
Trying out the astropy package template and cookiecutter was one of the outcomes of the discussion: that we had in https://innerspace.stsci.edu/pages/viewpage.action?pageId=118788324

I'm okay with this not being merged into master while we try it out, and see what things might need to be added/replaced, or change.  But I did want something in place for a comparison and to start testing and using it.

**Comment by sosey** [comment]
I think it will be pretty confusing to users, who will arguably be mostly non-fulltime software devs to have one repository, with two different branches representing fairly different package templates and dependencies. 

If this has been chosen as the best way to present the templates, then the readme should include information for the user on which one they should choose, and why; And this information should be propagated to the master branch's readme as well. There will probably be many internal users who wont be using astropy in their code, saddling their package with all the dependencies that come with  the astropy template might not be their best path. If we do this, lets change the name of the master branch to something more instructive. 

That said, the readme should be fixed to change cookiecutter to stsci-cookiecutter to match the branch name

`cookiecutter https://github.com/spacetelescope/stsci-package-template --checkout cookiecutter`

should be

`cookiecutter https://github.com/spacetelescope/stsci-package-template --checkout stsci-cookiecutter`

Also, the license section is confusing, I don't know of an Aura license, just an Aura Copyright, I think that option should be removed, "other" should also be reconsidered if we're required to have a specific non-viral license. I think the AURA Copyright should probably be included in every repository, in addition to the license that is chosen. the Copyright guards intellectual property, the license informs use. They are included in one file in the master repo, but perhaps they should be separated. Maybe @arfon has suggestions?

The link text for `This template's Github code repository` should be changed to `The Astropy Template Github code repository` for clarity, or link it to this stsci one

The questions presented by the cookiecutter wont make immediate sense to new and possibly intermediate users, the readme should either point to documentation that explains each of the questions and what they mean, or include descriptions of them in the readme itself. The users should see them before running cookiecutter so they understand. Minimally include a link to the `QUESTIONS.rst` that has some descriptions. 

 I'm referring to the questions asked during setup:
```
Select license:
1 - Aura
2 - BSD 3-Clause
3 - GNU GPL v3+
4 - Apache Software Licence 2.0
5 - BSD 2-Clause
6 - Other
project_url [http://stsci.edu]: 
project_version [0.0.dev]: 
include_example_code [y]: 
include_example_cython_code [n]: 
include_cextern_folder [n]: 
edit_on_github_extension [False]: 
github_project [spacetelescope/stsci-package-template]:
use_travis_ci [y]: 
use_appveyor_ci [n]: 
use_read_the_docs [y]: 
sphinx_theme [stsci_rtd_theme]: 
initialize_git_repo [y]: 
Select minimum_python_version:
1 - 3.7
2 - 3.6
3 - 3.5
Choose from 1, 2, 3 [1]: 
astropy_helpers_version [v3.0.2]: 
```

**Comment by stscicrawford** [comment]
Thanks for the great comments @sosey and definitely the catch on the wrong command!

If you'd prefer me to update both README's with information point back to each other, then I'll go ahead with it.    I didn't want to make this the main one prior to some people having tried it out and given feedback, but if you think it would reduce confusing then we could always switch it back if this doesn't work out. 

I think it is safe to assume that the majority of our python packages developed at the institute for functional work that will be on github will have astropy as a dependency.   I realize that it is a little more overhead, but I think a number of packages being created by INS currently are using the template package.  Nonetheless, I fully support  providing people the option and then they can choose according to what they need or would prefer with the appropriate information to choose between the two.    As yo mention above this just needs clear instructions. 

Following python and Tom R. , I'd suggest 'legacy' for the other branch. 

I could just update all the licenses to have the Aura copyright.   That would probably be easiest and reduce the confusion.   Though, I 'd agree if the copyright and the license should be separate is a good question for @arfon. 

The questions won't be fixed in this pull request, but I'll open a second issue so that it is tracked.

**Comment by arfon** [comment]
> My experience working with people at the institute makes me prefer the original template, without the astropy-helpers dependency. That's the biggest issue for me. Most everyone will already have astropy in their environment as it's in both our dev and astroconda environments, so making it a dependency by default is reasonable, but the helpers package becoming a dependency adds other issues.

Can we discuss this? From talking with folks here it's clear this is a contentious issue. I've spoken to multiple people both at STScI and externally who either believe 1) astropy-helpers is ✨ or 2) astropy-helpers is 😡. 

With no personal experience of using this library I'm not qualified to pass judgement but I suspect we should have a broader discussion in DATB/SCSB/DMD about whether we think our colleagues at STScI by default should be using this package.

**Comment by jhunkeler** [comment]
Thoughts:

1) A package that (a) imports `astropy` and (b) uses it for something more than `pytest` and (c) requires astropy template specific features: applies the `astropy-helpers` template.

2) A package that does not (a) import `astropy` or (b) imports astropy for `pytest` facilities and (c) does not require astropy template specific features: applies `stsci-package-template`.

3) The developer agrees to incorporate any mandatory files from `stsci-package-template` without using the template directly. Everything regarding project structure and/or the build system (`make`, `cmake`, `scons`, etc) implementation falls to the developer. (Applicable to Dockerfile, Shell script libraries, C, C++, Fortran, D, Go, and even Python))

**i.e.**

Astropy's package template should be avoided if a project does not use `astropy` and has nothing to do with Astronomy. If that's the case and you still don't know how to structure your software, then use `stsci-package-template`. Finally, if you already know how to do all of these things, you can do whatever you like as long you include the AURA BSD-3clause license (because your software is not really yours, sorry to say), CoC and Contributing Guide.

**Comment by stscicrawford** [comment]
For discussion about astropy helpers, I've opened up an issue here:
https://github.com/spacetelescope/style-guides/issues/37

**Comment by eteq** [comment]
Good timing: I was *just* about to post in spacetelescope/stsci-package-template#16 ... so see there for the context of this message (cc @sosey @arfon)

An important bit of context regarding the helpers: *part* of the motivation was to lower the mental burden on scientists who aren't going to take the time to become deep experts in packaging. i.e., they can learn how to write docstrings that get rendered in sphinx without knowing much about sphinx, or unit tests using remote data without really understanding `pytest` or the details of the remote-data plugin. By creating shared infrastructure for that  it's easier for the community to share support for such things, so people who are experts in the shared infrastructure can support a larger group of the community.

But all that goes out the window if the audience are all people who *already* experts in such things.  In my experience that's the crowd that is more likely to be 😡 - if they already know how to do this stuff so they see the helpers as getting in the way.  So that leads to the *second* motivation of the helpers: to provide shared infrastructure for these things so that at least we *share* the maintenance burden instead of everyone rolling their own.  I would argue that this is still a worthwhile goal, but if it really *is* too much of a burden that's an argument to simplify the helpers machinery, but *not* to throw it away completely in favor of something else.

So I guess I don't agree with the last part @jhunkeler says:  we can't say "use a different template if it's not astro-related" - it's all astro-related because we are producing software for the astronomy community, and we end up paying for it in the end anyway if we can't lower the maintainence burden on the folks who are 😡 about the template.

**Comment by pllim** [comment]
Just gonna merge this and follow up separately.

**Pull request merged**
